apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector: 
    matchLabels:
      app: {{ .Values.client.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.selector }}
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.client.service.targetPort }}
          env:
            - name: NODE_ENV
              value: production-kubernetes
