apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-microservice-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.genaiMicroservice.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.genaiMicroservice.selector }}
    spec:
      containers:
        - name: genai-microservice-container
          image: "{{ .Values.genaiMicroservice.image.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.genaiMicroservice.image.pullPolicy }}
          ports:
            - containerPort:
                {{ .Values.genaiMicroservice.service.targetPort }}
          env:
            - name: OLLAMA_BASE_URL
              value: "http://{{ .Values.ollama.service.name }}:11434"
          envFrom:
            - configMapRef:
                name: {{ .Values.backendEnvironmentConfigMapName }}
            - secretRef:
                name: {{ .Values.secretsName }}