apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.ollama.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.ollama.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.ollama.selector }}
    spec:
      containers:
        - name: ollama-container
          image: "{{ .Values.ollama.image.repository }}:{{ .Values.ollama.image.tag }}"
          imagePullPolicy: {{ .Values.ollama.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ollama.service.targetPort }}
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
      volumes:
        - name: ollama-data
          emptyDir: {}