apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.userMicroservice.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.userMicroservice.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.userMicroservice.selector }}
    spec:
      containers:
        - name: user-microservice-container
          image: "{{ .Values.userMicroservice.image.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.userMicroservice.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.userMicroservice.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.backendEnvironmentConfigMapName }}
            - secretRef:
                name: {{ .Values.secretsName }}
          volumeMounts:
            - name: jwt-secret-volume
              mountPath: /home/cnf/mentorpulse-certificates
              readOnly: true
      volumes:
        - name: jwt-secret-volume
          secret:
            secretName: jwt-secret