/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as TestImport } from './pages/test'
import { Route as IndexImport } from './pages/index'
import { Route as SearchIndexImport } from './pages/search/index'
import { Route as MentorMentorIdImport } from './pages/mentor.$mentorId'
import { Route as ApplicationsMentorMentorIdImport } from './pages/applications/mentor/$mentorId'
import { Route as ApplicationsMenteeMenteeIdImport } from './pages/applications/mentee/$menteeId'

// Create/Update Routes

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SearchIndexRoute = SearchIndexImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRoute,
} as any)

const MentorMentorIdRoute = MentorMentorIdImport.update({
  id: '/mentor/$mentorId',
  path: '/mentor/$mentorId',
  getParentRoute: () => rootRoute,
} as any)

const ApplicationsMentorMentorIdRoute = ApplicationsMentorMentorIdImport.update(
  {
    id: '/applications/mentor/$mentorId',
    path: '/applications/mentor/$mentorId',
    getParentRoute: () => rootRoute,
  } as any,
)

const ApplicationsMenteeMenteeIdRoute = ApplicationsMenteeMenteeIdImport.update(
  {
    id: '/applications/mentee/$menteeId',
    path: '/applications/mentee/$menteeId',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/mentor/$mentorId': {
      id: '/mentor/$mentorId'
      path: '/mentor/$mentorId'
      fullPath: '/mentor/$mentorId'
      preLoaderRoute: typeof MentorMentorIdImport
      parentRoute: typeof rootRoute
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexImport
      parentRoute: typeof rootRoute
    }
    '/applications/mentee/$menteeId': {
      id: '/applications/mentee/$menteeId'
      path: '/applications/mentee/$menteeId'
      fullPath: '/applications/mentee/$menteeId'
      preLoaderRoute: typeof ApplicationsMenteeMenteeIdImport
      parentRoute: typeof rootRoute
    }
    '/applications/mentor/$mentorId': {
      id: '/applications/mentor/$mentorId'
      path: '/applications/mentor/$mentorId'
      fullPath: '/applications/mentor/$mentorId'
      preLoaderRoute: typeof ApplicationsMentorMentorIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/mentor/$mentorId': typeof MentorMentorIdRoute
  '/search': typeof SearchIndexRoute
  '/applications/mentee/$menteeId': typeof ApplicationsMenteeMenteeIdRoute
  '/applications/mentor/$mentorId': typeof ApplicationsMentorMentorIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/mentor/$mentorId': typeof MentorMentorIdRoute
  '/search': typeof SearchIndexRoute
  '/applications/mentee/$menteeId': typeof ApplicationsMenteeMenteeIdRoute
  '/applications/mentor/$mentorId': typeof ApplicationsMentorMentorIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/mentor/$mentorId': typeof MentorMentorIdRoute
  '/search/': typeof SearchIndexRoute
  '/applications/mentee/$menteeId': typeof ApplicationsMenteeMenteeIdRoute
  '/applications/mentor/$mentorId': typeof ApplicationsMentorMentorIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/mentor/$mentorId'
    | '/search'
    | '/applications/mentee/$menteeId'
    | '/applications/mentor/$mentorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/mentor/$mentorId'
    | '/search'
    | '/applications/mentee/$menteeId'
    | '/applications/mentor/$mentorId'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/mentor/$mentorId'
    | '/search/'
    | '/applications/mentee/$menteeId'
    | '/applications/mentor/$mentorId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  MentorMentorIdRoute: typeof MentorMentorIdRoute
  SearchIndexRoute: typeof SearchIndexRoute
  ApplicationsMenteeMenteeIdRoute: typeof ApplicationsMenteeMenteeIdRoute
  ApplicationsMentorMentorIdRoute: typeof ApplicationsMentorMentorIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  MentorMentorIdRoute: MentorMentorIdRoute,
  SearchIndexRoute: SearchIndexRoute,
  ApplicationsMenteeMenteeIdRoute: ApplicationsMenteeMenteeIdRoute,
  ApplicationsMentorMentorIdRoute: ApplicationsMentorMentorIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/test",
        "/mentor/$mentorId",
        "/search/",
        "/applications/mentee/$menteeId",
        "/applications/mentor/$mentorId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/mentor/$mentorId": {
      "filePath": "mentor.$mentorId.tsx"
    },
    "/search/": {
      "filePath": "search/index.tsx"
    },
    "/applications/mentee/$menteeId": {
      "filePath": "applications/mentee/$menteeId.tsx"
    },
    "/applications/mentor/$mentorId": {
      "filePath": "applications/mentor/$mentorId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
