services:
  client:
    image: ghcr.io/aet-devops25/team-the-merge-doctors/client:latest
    ports:
      - 3000:80

  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ./docker/backend_config_files/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/backend_config_files/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./docker/backend_config_files/pg-hba.conf:/etc/postgresql/pg_hba.conf:ro

  user-service:
     image: ghcr.io/aet-devops25/team-the-merge-doctors/server/user-service:latest
     ports:
       - 8210:8210
     volumes:
       - $HOME/mentorpulse-certificates/jwt-secret.key:/home/cnf/mentorpulse-certificates/jwt-secret.key:ro
     depends_on:
       - postgres-db
     restart: on-failure:3

  genai:
    image: ghcr.io/aet-devops25/team-the-merge-doctors/genai:latest
    command: gunicorn -b 0.0.0.0:5001 app:app
    volumes:
      - ./genai:/app
    ports:
      - "5001:5001"
    environment:
    - POSTGRES_HOST=postgres-db
    env_file:
      - ./docker/backend_config_files/.env
    depends_on:
      - postgres-db
    restart: always

  mentorship-service:
    image: ghcr.io/aet-devops25/team-the-merge-doctors/server/mentorship-service:latest
    ports:
      - 8310:8310
    depends_on:
      - postgres-db
    restart: on-failure:3

  rating-service:
    image: ghcr.io/aet-devops25/team-the-merge-doctors/server/rating-service:latest
    ports:
      - 8410:8410
    depends_on:
      - postgres-db
    restart: on-failure:3

  appointment-service:
    image: ghcr.io/aet-devops25/team-the-merge-doctors/server/appointment-service:latest
    ports:
      - 8510:8510
    depends_on:
      - postgres-db
    restart: on-failure:3

volumes:
  db_data:
