services:
  client:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  postgres-db:
    platform: linux/amd64
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ./docker/backend_config_files/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/backend_config_files/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./docker/backend_config_files/pg-hba.conf:/etc/postgresql/pg_hba.conf:ro

  user-service:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/server/user-service:latest
    ports:
      - 8210:8210
    build:
      context: server/userservice
      dockerfile: Dockerfile
    volumes:
      - $HOME/mentorpulse-certificates/jwt-secret.key:/home/cnf/mentorpulse-certificates/jwt-secret.key:ro
    depends_on:
      - postgres-db
    restart: on-failure:3

  ollama:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/ollama:latest
    build:
      context: ./genai/ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  genai:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/genai:latest
    build:
      context: genai
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:5001 --config gunicorn.conf.py app:app
    volumes:
      - ./genai:/app
    ports:
      - "5001:5001"
    environment:
      - POSTGRES_HOST=postgres-db
      - OLLAMA_BASE_URL=http://ollama:11434
    env_file:
      - ./docker/backend_config_files/.env
    depends_on:
      - postgres-db
      - ollama
    restart: always

  mentorship-service:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/server/mentorship-service:latest
    build:
      context: server/mentorshipservice
      dockerfile: Dockerfile
    ports:
      - 8310:8310
    depends_on:
      - postgres-db
    restart: on-failure:3

  rating-service:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/server/rating-service:latest
    build:
      context: server/ratingservice
      dockerfile: Dockerfile
    ports:
      - 8410:8410
    depends_on:
      - postgres-db
    restart: on-failure:3

volumes:
  db_data:
  ollama_data:
