services:
  client:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - internal

  postgres-db:
    platform: linux/amd64
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ./docker/backend_config_files/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/backend_config_files/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./docker/backend_config_files/pg-hba.conf:/etc/postgresql/pg_hba.conf:ro
    networks:
      - internal

  user-service:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/server/user-service:latest
    ports:
      - 8210:8210
    expose:
      - "8211"  # Management port (internal monitoring only - don't expose in production), Only accessible to other containers in the network 
    networks:
      - internal
    build:
      context: server/userservice
      dockerfile: Dockerfile
    volumes:
      - $HOME/mentorpulse-certificates/jwt-secret.key:/home/cnf/mentorpulse-certificates/jwt-secret.key:ro
    depends_on:
      - postgres-db
    restart: on-failure:3

  ollama:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/ollama:latest
    build:
      context: ./genai/ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    networks:
      - internal

  genai:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/genai:latest
    build:
      context: genai
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:5001 --config gunicorn.conf.py app:app
    volumes:
      - ./genai:/app
    ports:
      - "5001:5001"
    environment:
      - POSTGRES_HOST=postgres-db
      - OLLAMA_BASE_URL=http://ollama:11434
    env_file:
      - ./docker/backend_config_files/.env
    depends_on:
      - postgres-db
      - ollama
    restart: always
    networks:
      - internal


  mentorship-service:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/server/mentorship-service:latest
    build:
      context: server/mentorshipservice
      dockerfile: Dockerfile
    ports:
      - 8310:8310
    environment:
      - AUTHORIZATION_ENABLED=false
    depends_on:
      - postgres-db
    restart: on-failure:3
    networks:
      - internal

  rating-service:
    platform: linux/amd64
    image: ghcr.io/aet-devops25/team-the-merge-doctors/server/rating-service:latest
    build:
      context: server/ratingservice
      dockerfile: Dockerfile
    ports:
      - 8410:8410
    depends_on:
      - postgres-db
    restart: on-failure:3
    networks:
      - internal

  prometheus:
    platform: linux/amd64
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/rules.yml:/etc/prometheus/rules.yml:ro
      - prometheus_data:/prometheus
    command:
      # Path to Prometheus configuration file
      - '--config.file=/etc/prometheus/prometheus.yml'
      # Directory to store time series data
      - '--storage.tsdb.path=/prometheus'
      # Path to console libraries for web UI
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      # Path to console templates for web UI
      - '--web.console.templates=/etc/prometheus/consoles'
      # Enable HTTP endpoints for graceful shutdown and reload
      - '--web.enable-lifecycle'
    networks:
      - internal
    restart: unless-stopped

  grafana:
    platform: linux/amd64
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/provisioning/notifiers:/etc/grafana/provisioning/notifiers:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ALERTING_ENABLED=true  
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - internal
  

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/backend_config_files/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - user-service
      - mentorship-service
      - rating-service
      - genai

volumes:
  db_data:
  prometheus_data:
  grafana_data:
  ollama_data:

networks:
  internal:
    driver: bridge
