apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backendEnvironmentConfigMapName }}
data:
  FLASK_ENV: development
  FLASK_APP: app.py
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_GEN_AI_DB: genai_backend