# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ .Values.postgresDb.persistentVolume }}
#   labels:
#     app: {{ .Values.postgresDb.selector }}
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi

# TODO: probably delete