apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretsName }}
data:
  OPENAI_API_KEY: {{ .Values.secrets.openAPIKey | b64enc }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc }}