apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretsName }}
data:
  OPENAI_API_KEY: {{ .Values.secrets.openAPIKey }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}