server:
  port: 8310
postgres:
  ip: postgres-db
  port: 5432
  db-name: mentorship_backend

spring:
  application:
    name: mentorship-service
  datasource:
    password: qweasdzxc
    username: merge_doctor_backend
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${postgres.ip}:${postgres.port}/${postgres.db-name}
  jpa:
    generate-ddl: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
