services:
  client:
    image: ghcr.io/aet-devops25/team-the-merge-doctors/client:latest
    ports:
      - 3000:80

  user-service:
    image: ghcr.io/aet-devops25/team-the-merge-doctors/server/user-service:latest
    ports:
      - 8000:8080
