namespace: team-the-merge-doctors

user-microservice:
  image:
    repository:
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8000
  replicaCount: 1

genai-microservice:
  image:
    repository:
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5001
    targetPort: 5001
  replicaCount: 1

client:
  image:
    repository:
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
    targetPort: 80
  replicaCount: 1
  selector: client-selector
