services:
  db:
    image: postgres:15
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./pg-hba.conf:/etc/postgresql/pg_hba.conf:ro

  genai:
    build:
      context: ../../genai
      dockerfile: ./Dockerfile
    command: gunicorn -b 0.0.0.0:5001 app:app
    volumes:
      - ../../genai:/app
    ports:
      - "5001:5001"
    environment:
    - POSTGRES_HOST=db
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: