apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.genai-microservice.selector }}
  ports:
    - port: {{ .Values.genai-microservice.service.port }}
      targetPort: {{ .Values.genai-microservice.service.targetPort }}
      protocol: TCP
  type: {{ .Values.genai-microservice.service.type }}