spring:
  application:
    name: gateway
server:
  port: 8610

services:
  user:
    url: http://user-service:8210

info:
  title: Gateway Service.
  description: Gateway Service for Mentorpulse microservices.
  version: 1.0.0