apiVersion: 1

datasources:
  # Prometheus datasource configuration for mentorship service monitoring
  - name: Prometheus
    type: prometheus
    # Access mode: proxy (Grafana acts as a reverse proxy to prometheus)
    access: proxy
    # URL of the Prometheus server (using Docker service name)
    url: http://prometheus:9090
    # Set as the default datasource for new dashboards
    isDefault: true

