apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userMicroservice.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.userMicroservice.selector }}
  ports:
    - port: {{ .Values.userMicroservice.service.port }}
      targetPort: {{ .Values.userMicroservice.service.targetPort }}
      protocol: TCP
  type: {{ .Values.userMicroservice.service.type }}
