name: Backend tests

on:
  workflow_call:

permissions: write-all

jobs:
  run-backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Run User Service tests
        working-directory: ./server/userservice
        run: ./gradlew test

      - name: Run Mentorship Service tests
        working-directory: ./server/mentorshipservice
        run: ./gradlew test

      - name: Run Rating Service tests
        working-directory: ./server/ratingservice
        run: ./gradlew test

      - name: Upload backend test reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: |
            server/userservice/build/reports/tests/test
            server/mentorshipservice/build/reports/tests/test
            server/ratingservice/build/reports/tests/test
