name: CI – Build & Publish

on:
  push:
  pull_request:
  workflow_call:

permissions: write-all

jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push Client image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: ghcr.io/aet-devops25/team-the-merge-doctors/client:latest

      - name: Build & push GenAI image
        uses: docker/build-push-action@v4
        with:
          context: ./genai
          push: true
          tags: ghcr.io/aet-devops25/team-the-merge-doctors/genai:latest

      - name: Build & push User Service image
        uses: docker/build-push-action@v4
        with:
          context: ./server/user
          push: true
          tags: ghcr.io/aet-devops25/team-the-merge-doctors/server/user-service:latest
