name: Manual k8s (Helm) deployment

on:
  workflow_call:

jobs:
  kubernetes_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up kubeconfig
        run: |
          mkdir $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          echo $HOME/.kube/config

      - name: Test Kubernetes connectivity
        run: kubectl get nodes

      - name: Deploy using Helm
        run: |
          helm upgrade --install mentor-pulse ./helm/ \
            --namespace team-the-merge-doctors \
            --set tag=latest
            --debug
        env:
          KUBECONFIG: $HOME/.kube/config
