name: Manual k8s (Helm) deployment

on:
  workflow_dispatch:
    inputs:
      open_api_key:
        description: "Your Open API key"
        required: true

jobs:
  kubernetes_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      # TODO: we are currently just using the latest containers without building them beforehand. Maybe add deployment as step of the pipeline on commits on the main branch
      - name: Replace OPEN API key
        run: |
          cp ./helm/values.yaml.template ./helm/values.yaml
          sed -i 's/<YOUR_OPEN_API_KEY>/${{ github.event.inputs.open_api_key }}/g' ./helm/values.yaml

      - name: Deploy using Helm
        run: |
          helm upgrade --install mentor-pulse ./helm/ \
            --namespace default \
            --create-namespace \
