name: k8s (Helm) deployment

on:
  workflow_call:

jobs:
  kubernetes_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug secret access
        run: |
          echo "${{ secrets.KUBECONFIG }}" || echo "Failed to access KUBECONFIG secret."

      - name: Debug kubeconfig decoding
        run: |
          echo "$KUBECONFIG_64" | base64 --decode || echo "Failed to decode KUBECONFIG secret."

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Verify cluster access
        run: |
          kubectl version
          kubectl get nodes
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Deploy using Helm
        run: |
          helm upgrade --install mentor-pulse ./helm/ \
            --namespace team-the-merge-doctors \
            --set tag=latest \
            --debug
