name: k8s (Helm) deployment

on:
  workflow_call:

jobs:
  kubernetes_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug secret access
        run: |
          echo "${{ secrets.KUBECONFIG }}" || echo "Failed to access KUBECONFIG secret."

      - name: Debug kubeconfig decoding
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode || echo "Failed to decode KUBECONFIG secret."

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          echo "KUBECONFIG=~/.kube/config" >> $GITHUB_ENV

      - name: Deploy using Helm
        run: |
          helm upgrade --install mentor-pulse ./helm/ \
            --namespace team-the-merge-doctors \
            --set tag=latest \
            --debug
