name: k8s (Helm) deployment

on:
  workflow_call:
    secrets:
      KUBECONF:
        description: "Base64‑encoded kubeconfig file"
        required: true

jobs:
  kubernetes_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONF }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          echo "KUBECONF=~/.kube/config" >> $GITHUB_ENV

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONF_B64" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          echo "KUBECONF=~/.kube/config" >> $GITHUB_ENV
        env:
          KUBECONF_B64: ${{ secrets.KUBECONF }}

      - name: Deploy using Helm
        env:
          KUBECONF: ${{ runner.home }}/.kube/config
        run: |
          helm upgrade --install mentor-pulse ./helm/ \
            --namespace team-the-merge-doctors \
            --set tag=${{ github.sha }}} \
            --debug
